"""
序话Story Logo 概念生成脚本
使用 NB2 (gemini-3.1-flash-image-preview) 生成 3 个概念方向的 logo

用法: python scripts/generate_logo_concepts.py
输出: test_output/manualtest/logo_concepts/
"""

import asyncio
import os
import sys
import time
from io import BytesIO
from pathlib import Path

# 项目根目录
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv
load_dotenv(PROJECT_ROOT / ".env")

from google import genai
from google.genai import types
from PIL import Image

NB2_MODEL = "gemini-3.1-flash-image-preview"
OUTPUT_DIR = PROJECT_ROOT / "test_output" / "manualtest" / "logo_concepts"

# ============================================================
# 反 AI 感的通用约束（附加到每个 prompt 末尾）
# ============================================================
ANTI_AI_CONSTRAINTS = """
CRITICAL STYLE REQUIREMENTS:
- Flat vector logo design, professional logo designer quality
- Solid single color only: pure black (#000000) shape on pure white (#FFFFFF) background
- NO gradients, NO 3D effects, NO shadows, NO textures, NO glow, NO highlights
- NO hexagons, NO swirls, NO spirals, NO starburst patterns, NO neural network imagery
- NO text, NO letters, NO words, NO characters of any language
- Clean, bold, minimalist lines with slight hand-drawn warmth (not perfectly mechanical)
- Must be recognizable at 16px favicon size AND 1024px app icon size
- Simple enough to be drawn in one continuous stroke concept
- The icon should feel like it was designed by a top-tier human logo designer, NOT generated by AI
- Think Paul Rand, Aaron Draplin, Paula Scher level of design sophistication
- Centered composition within a square canvas with balanced negative space
"""

# ============================================================
# 3 个概念方向的 prompt
# ============================================================
CONCEPTS = {
    "A_play_bubble": {
        "name": "方向A：播放键×对话气泡",
        "prompts": [
            # 变体 1：纯几何融合
            f"""Design a minimalist logo icon that cleverly merges a PLAY BUTTON triangle (▶) with a SPEECH BUBBLE shape into one unified symbol. The play triangle forms the main body of the speech bubble, with the bubble's tail extending from the lower-left corner. Bold, confident stroke weight. The shape should have a subtle warmth — not cold and mechanical, but inviting. Imagine pressing play on the movie inside your head, and the story starts speaking.
{ANTI_AI_CONSTRAINTS}""",

            # 变体 2：圆内嵌套
            f"""Design a minimalist logo icon: a circle containing a play button triangle (▶) that simultaneously reads as a speech/dialogue bubble when you look at the negative space. The circle represents a screen or spotlight, the triangle is both "play" and "voice." One unified mark, not two separate symbols layered on top of each other. Bold and playful but warm.
{ANTI_AI_CONSTRAINTS}""",

            # 变体 3：更抽象的诠释
            f"""Design a minimalist abstract logo icon that captures the concept of "pressing play on a conversation" or "a story beginning to speak." Combine the essence of a forward-pointing arrow or play symbol with the essence of a speech bubble into one simple, clever, unified geometric mark. The mark should feel dynamic and alive, like something is about to begin. Bold stroke, slightly rounded corners for warmth.
{ANTI_AI_CONSTRAINTS}""",
        ]
    },

    "B_frame_flip": {
        "name": "方向B：电影帧×翻页",
        "prompts": [
            # 变体 1：胶片帧翻角
            f"""Design a minimalist logo icon that looks like a single film frame or photograph with its top-right corner curling/peeling upward, as if a page is being turned to reveal the next chapter. The frame is a simple rounded rectangle. Two small squares (film sprocket holes) on the left edge. The curling corner creates a sense of motion and anticipation — a story about to unfold. Warm, inviting, slightly playful.
{ANTI_AI_CONSTRAINTS}""",

            # 变体 2：更简化的翻页
            f"""Design a minimalist logo icon: a simple square or rounded rectangle representing a screen/frame/canvas, with one corner (top-right) elegantly folded or lifted, like turning a page. The fold reveals a small triangular area underneath, suggesting hidden depth and stories waiting to be told. Clean, bold lines. The overall feeling should be like opening a book to its first page — the prologue moment.
{ANTI_AI_CONSTRAINTS}""",

            # 变体 3：多层帧叠加
            f"""Design a minimalist logo icon showing two overlapping rectangular frames (like stacked film frames or pages), with the top one slightly offset and its corner lifting up. This creates a sense of sequence and narrative progression — one scene following another, like flipping through a visual story. Simple, bold outlines only, no fill. The slight offset gives it personality and avoids rigid AI-like symmetry.
{ANTI_AI_CONSTRAINTS}""",
        ]
    },

    "C_curtain_reveal": {
        "name": "方向C：展开的帘幕",
        "prompts": [
            # 变体 1：圆内弧线掀幕
            f"""Design a minimalist logo icon: a circle (representing a spotlight or screen) with an elegant curved line inside that sweeps from bottom-left to top-right, as if a curtain is being pulled open to reveal the stage. The curve has calligraphic quality — thicker at the start, tapering toward the end, like a confident brushstroke. The negative space between the curve and the circle edge suggests the opening, the beginning, the prologue moment. Bold, dramatic, yet warm.
{ANTI_AI_CONSTRAINTS}""",

            # 变体 2：半开的门/窗
            f"""Design a minimalist logo icon that looks like a rounded rectangle or arch (representing a doorway, window, or screen) that is partially open — one side swinging inward, creating a wedge of negative space that invites you in. The concept is "a portal opening to your story world." Simple, architectural, bold. One continuous outline with the opening creating visual intrigue. Warm and inviting, not cold or sterile.
{ANTI_AI_CONSTRAINTS}""",

            # 变体 3：抽象卷轴展开
            f"""Design a minimalist logo icon that abstractly represents a scroll or curtain unfurling. A single bold curved line spirals gently outward from a central point, like the first stroke of a Chinese calligrapher's brush beginning a new piece, or like a film reel unwinding to start the show. NOT a spiral or swirl — more like one confident, decisive curve that suggests "beginning" and "opening." Asymmetric, organic, with brushstroke-like thickness variation.
{ANTI_AI_CONSTRAINTS}""",
        ]
    },
}


async def generate_single_image(
    client: genai.Client,
    prompt: str,
    output_path: Path,
    label: str,
) -> bool:
    """生成单张 logo 图片"""
    print(f"\n  [{label}] 开始生成...")
    start = time.time()

    try:
        response = await client.aio.models.generate_content(
            model=NB2_MODEL,
            contents=[prompt],
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio="1:1",
                ),
            ),
        )

        # 提取图片
        for part in response.parts:
            if part.inline_data is not None:
                genai_image = part.as_image()

                # 转换为 PIL Image（多策略回退）
                pil_image = None
                if hasattr(genai_image, '_pil_image') and genai_image._pil_image:
                    pil_image = genai_image._pil_image
                elif hasattr(genai_image, 'data'):
                    pil_image = Image.open(BytesIO(genai_image.data))
                else:
                    try:
                        buf = BytesIO()
                        genai_image.save(buf)
                        buf.seek(0)
                        pil_image = Image.open(buf)
                    except Exception:
                        import base64
                        image_bytes = base64.b64decode(part.inline_data.data)
                        pil_image = Image.open(BytesIO(image_bytes))

                if pil_image:
                    pil_image.save(str(output_path), "PNG")
                    elapsed = round(time.time() - start, 1)
                    print(f"  [{label}] ✅ 成功 — {pil_image.width}x{pil_image.height}, {elapsed}s → {output_path.name}")
                    return True

        print(f"  [{label}] ❌ 响应中无图片数据")
        return False

    except Exception as e:
        elapsed = round(time.time() - start, 1)
        print(f"  [{label}] ❌ 失败 ({elapsed}s): {e}")
        return False


async def main():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ GEMINI_API_KEY 未设置")
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("序话Story Logo 概念生成")
    print(f"模型: {NB2_MODEL}")
    print(f"输出: {OUTPUT_DIR}")
    print(f"计划: 3 方向 × 3 变体 = 9 张")
    print("=" * 60)

    total_start = time.time()
    results = {"success": 0, "fail": 0}

    for concept_key, concept in CONCEPTS.items():
        concept_dir = OUTPUT_DIR / concept_key
        concept_dir.mkdir(parents=True, exist_ok=True)

        print(f"\n{'─' * 50}")
        print(f"📐 {concept['name']}")
        print(f"{'─' * 50}")

        for i, prompt in enumerate(concept["prompts"], 1):
            filename = f"{concept_key}_v{i}.png"
            output_path = concept_dir / filename
            label = f"{concept_key}_v{i}"

            # 保存 prompt 到同名 .txt
            prompt_path = concept_dir / f"{concept_key}_v{i}_prompt.txt"
            prompt_path.write_text(prompt, encoding="utf-8")

            success = await generate_single_image(client, prompt, output_path, label)
            if success:
                results["success"] += 1
            else:
                results["fail"] += 1

            # API 限速保护
            await asyncio.sleep(2)

    total_elapsed = round(time.time() - total_start, 1)

    print(f"\n{'=' * 60}")
    print(f"✅ 完成: {results['success']}/9 成功, {results['fail']}/9 失败")
    print(f"⏱  总耗时: {total_elapsed}s")
    print(f"📁 输出目录: {OUTPUT_DIR}")
    print(f"{'=' * 60}")

    # 列出生成的文件
    print("\n生成的文件:")
    for concept_key in CONCEPTS:
        concept_dir = OUTPUT_DIR / concept_key
        pngs = sorted(concept_dir.glob("*.png"))
        for p in pngs:
            size = p.stat().st_size // 1024
            print(f"  {concept_key}/{p.name} ({size}KB)")


if __name__ == "__main__":
    asyncio.run(main())
