"""
序话Story Logo 混合方向生成：A_v2 的干净结构 + C_v1 的书法质感
"""

import asyncio
import os
import sys
import time
from io import BytesIO
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv
load_dotenv(PROJECT_ROOT / ".env")

from google import genai
from google.genai import types
from PIL import Image

NB2_MODEL = "gemini-3.1-flash-image-preview"
OUTPUT_DIR = PROJECT_ROOT / "test_output" / "manualtest" / "logo_concepts" / "D_hybrid"

ANTI_AI_CONSTRAINTS = """
CRITICAL STYLE REQUIREMENTS:
- Flat vector logo design, professional logo designer quality
- Solid single color only: pure black (#000000) shape on pure white (#FFFFFF) background
- NO gradients, NO 3D effects, NO shadows, NO textures, NO glow, NO highlights
- NO hexagons, NO swirls, NO spirals, NO starburst patterns, NO neural network imagery
- NO text, NO letters, NO words, NO characters of any language
- Must be recognizable at 16px favicon size AND 1024px app icon size
- The icon should feel like it was designed by a top-tier human logo designer, NOT generated by AI
- Think Paul Rand, Aaron Draplin, Paula Scher level of design sophistication
- Centered composition within a square canvas with balanced negative space
"""

HYBRID_PROMPTS = [
    # 变体 1：圆形+播放三角+气泡缺口，但线条带书法粗细变化
    f"""Design a minimalist logo icon: a circle with a play button triangle inside, where the circle has a small speech bubble notch at the bottom-left. The KEY DIFFERENTIATOR: the circle and triangle are drawn with calligraphic brush-stroke quality — the lines have elegant thickness variation, thicker on downstrokes and thinner on upstrokes, like confident East Asian ink brush strokes. Not rough or messy, but refined and intentional, like a master calligrapher drew it in one fluid motion. The overall structure is clean and geometric (circle + triangle + bubble notch), but the LINE QUALITY has organic warmth and hand-crafted elegance. Bold, warm, inviting.
{ANTI_AI_CONSTRAINTS}""",

    # 变体 2：播放键气泡结构，整体用一笔书法线条勾勒
    f"""Design a minimalist logo icon that combines a play button and speech bubble into one unified mark, drawn as if with a single continuous calligraphic brush stroke. The shape: a circle that opens into a speech bubble tail at bottom-left, with a triangular play symbol formed by negative space inside. The entire outline should feel like one flowing East Asian brush stroke — confident, elegant, with natural thickness variation (thick-to-thin transitions). NOT a spiral or swirl. The mark should feel both modern (play button, speech bubble) and timeless (brush stroke quality). Simple, bold, distinctive.
{ANTI_AI_CONSTRAINTS}""",

    # 变体 3：圆内播放三角，但圆本身是书法弧线构成（非完美圆），带气泡尾
    f"""Design a minimalist logo icon: imagine a calligrapher drawing a circle in one bold ink stroke — the circle is confident but not perfectly geometric, with natural brush-stroke thickness variation and a slight organic imperfection that gives it life. Inside this brush-drawn circle sits a clean, solid play button triangle (▶). At the lower-left, the circle's stroke tapers into a small speech bubble tail. The contrast between the organic calligraphic circle and the clean geometric triangle creates visual tension and personality. The overall feeling: East meets West, tradition meets modernity, artistry meets technology. Bold, warm, playful yet sophisticated.
{ANTI_AI_CONSTRAINTS}""",
]


async def generate_single(client, prompt, output_path, label):
    print(f"\n  [{label}] 开始生成...")
    start = time.time()
    try:
        response = await client.aio.models.generate_content(
            model=NB2_MODEL,
            contents=[prompt],
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(aspect_ratio="1:1"),
            ),
        )
        for part in response.parts:
            if part.inline_data is not None:
                img = part.as_image()
                pil = None
                if hasattr(img, '_pil_image') and img._pil_image:
                    pil = img._pil_image
                elif hasattr(img, 'data'):
                    pil = Image.open(BytesIO(img.data))
                else:
                    buf = BytesIO()
                    img.save(buf)
                    buf.seek(0)
                    pil = Image.open(buf)
                if pil:
                    pil.save(str(output_path), "PNG")
                    print(f"  [{label}] ✅ {pil.width}x{pil.height}, {round(time.time()-start,1)}s")
                    return True
        print(f"  [{label}] ❌ 无图片数据")
        return False
    except Exception as e:
        print(f"  [{label}] ❌ {e}")
        return False


async def main():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ GEMINI_API_KEY 未设置")
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print("混合方向：A_v2 结构 + C_v1 书法质感")
    print("=" * 50)

    for i, prompt in enumerate(HYBRID_PROMPTS, 1):
        path = OUTPUT_DIR / f"D_hybrid_v{i}.png"
        (OUTPUT_DIR / f"D_hybrid_v{i}_prompt.txt").write_text(prompt, encoding="utf-8")
        await generate_single(client, prompt, path, f"D_hybrid_v{i}")
        await asyncio.sleep(2)

    print("\n✅ 完成")


if __name__ == "__main__":
    asyncio.run(main())
